//for users
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'

export const USER_CATEGORY_LIST_REQUEST = 'USER_CATEGORY_LIST_REQUEST'
export const USER_CATEGORY_LIST_SUCCESS = 'USER_CATEGORY_LIST_SUCCESS'
export const USER_CATEGORY_LIST_FAIL = 'USER_CATEGORY_LIST_FAIL'

//for categories
export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST'
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL'

export const CATEGORY_DETAILS_REQUEST = 'CATEGORY_DETAILS_REQUEST'
export const CATEGORY_DETAILS_SUCCESS = 'CATEGORY_DETAILS_SUCCESS'
export const CATEGORY_DETAILS_FAIL = 'CATEGORY_DETAILS_FAIL'

export const CATEGORY_CREATE_REQUEST = 'CATEGORY_CREATE_REQUEST'
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS'
export const CATEGORY_CREATE_FAIL = 'CATEGORY_CREATE_FAIL'

export const CATEGORY_WITH_BOOKMARKS_CREATE_REQUEST =
  'CATEGORY_WITH_BOOKMARKS_CREATE_REQUEST'
export const CATEGORY_WITH_BOOKMARKS_CREATE_SUCCESS =
  'CATEGORY_WITH_BOOKMARKS_CREATE_SUCCESS'
export const CATEGORY_WITH_BOOKMARKS_CREATE_FAIL =
  'CATEGORY_WITH_BOOKMARKS_CREATE_FAIL'

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST'
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS'
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL'

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST'
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS'
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL'

//for bookmarks
export const BOOKMARK_CREATE_REQUEST = 'BOOKMARK_CREATE_REQUEST'
export const BOOKMARK_CREATE_SUCCESS = 'BOOKMARK_CREATE_SUCCESS'
export const BOOKMARK_CREATE_FAIL = 'BOOKMARK_CREATE_FAIL'

export const BOOKMARK_DETAILS_REQUEST = 'BOOKMARK_DETAILS_REQUEST'
export const BOOKMARK_DETAILS_SUCCESS = 'BOOKMARK_DETAILS_SUCCESS'
export const BOOKMARK_DETAILS_FAIL = 'BOOKMARK_DETAILS_FAIL'

export const BOOKMARK_UPDATE_REQUEST = 'BOOKMARK_UPDATE_REQUEST'
export const BOOKMARK_UPDATE_SUCCESS = 'BOOKMARK_UPDATE_SUCCESS'
export const BOOKMARK_UPDATE_FAIL = 'BOOKMARK_UPDATE_FAIL'

export const BOOKMARK_DELETE_REQUEST = 'BOOKMARK_DELETE_REQUEST'
export const BOOKMARK_DELETE_SUCCESS = 'BOOKMARK_DELETE_SUCCESS'
export const BOOKMARK_DELETE_FAIL = 'BOOKMARK_DELETE_FAIL'
